---
openapi: 3.0.1
info:
  title: API V1
  version: v1
components:
  schemas:
    reservations:
      sample1:
        type: object
        properties:
          reservation_code:
            type: string
          start_date:
            type: string
          end_date:
            type: string
          nights:
            type: number
          guests:
            type: number
          adults:
            type: number
          children:
            type: number
          infants:
            type: number
          status:
            type: string
          guest:
            type: object
            properties:
              first_name:
                type: string
              last_name:
                type: string
              phone:
                type: string
              email:
                type: string
          currency:
            type: string
          payout_price:
            type: string
          security_price:
            type: string
          total_price:
            type: string
      sample2:
        type: object
        properties:
          reservation:
            type: object
            properties:
              code:
                type: string
              start_date:
                type: string
              end_date:
                type: string
              expected_payout_amount:
                type: string
              guest_details:
                type: object
                properties:
                  localized_description:
                    type: string
                  number_of_adults:
                    type: number
                  number_of_children:
                    type: number
                  number_of_infants:
                    type: number
              guest_email:
                type: string
              guest_first_name:
                type: string
              guest_last_name:
                type: string
              guest_phone_numbers:
                type: array
                items:
                  type: string
              listing_security_price_accurate:
                type: string
              host_currency:
                type: string
              nights:
                type: number
              number_of_guests:
                type: number
              status_type:
                type: string
              total_paid_amount_accurate:
                type: string
paths:
  "/reservations":
    post:
      summary: create_or_update reservation
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                  message:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/reservations/sample1"
              - "$ref": "#/components/schemas/reservations/sample2"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
